# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "build_characters", :force => true do |t|
    t.column "build_id",     :integer
    t.column "character_id", :integer
    t.column "slot",         :integer
    t.column "alternate",    :integer
  end

  create_table "builds", :force => true do |t|
    t.column "owner_id",    :integer
    t.column "viewer_id",   :integer
    t.column "name",        :string
    t.column "created_at",  :datetime, :null => false
    t.column "updated_at",  :datetime, :null => false
    t.column "size",        :integer
    t.column "description", :text
    t.column "is_team",     :boolean
    t.column "is_pve",      :boolean
    t.column "build_type",  :string
  end

  create_table "character_attrs", :force => true do |t|
    t.column "character_id", :integer
    t.column "code",         :integer
    t.column "value",        :integer
    t.column "rune",         :integer
  end

  create_table "character_items", :force => true do |t|
    t.column "character_id", :integer
    t.column "where",        :string
    t.column "base",         :integer
    t.column "color",        :integer
    t.column "mod1",         :integer
    t.column "mod2",         :integer
    t.column "mod3",         :integer
  end

  create_table "character_skills", :force => true do |t|
    t.column "character_id", :integer
    t.column "code",         :integer
    t.column "slot",         :integer
    t.column "alternate",    :integer
  end

  create_table "characters", :force => true do |t|
    t.column "name",               :string
    t.column "level",              :integer
    t.column "attr_bonus_pts",     :integer
    t.column "primary_code",       :integer
    t.column "secondary_code",     :integer
    t.column "headgear_attr_code", :integer
    t.column "description",        :text
  end

  create_table "group_events", :force => true do |t|
    t.column "group_id",   :integer,  :null => false
    t.column "created_at", :datetime, :null => false
    t.column "event",      :string
  end

  create_table "group_users", :force => true do |t|
    t.column "group_id", :integer,                :null => false
    t.column "user_id",  :integer,                :null => false
    t.column "role",     :integer, :default => 0
  end

  create_table "groups", :force => true do |t|
    t.column "name",       :string
    t.column "rev",        :integer,  :default => 1, :null => false
    t.column "created_at", :datetime,                :null => false
  end

  create_table "open_id_authentication_associations", :force => true do |t|
    t.column "server_url", :binary
    t.column "handle",     :string
    t.column "secret",     :binary
    t.column "issued",     :integer
    t.column "lifetime",   :integer
    t.column "assoc_type", :string
  end

  create_table "open_id_authentication_nonces", :force => true do |t|
    t.column "nonce",   :string
    t.column "created", :integer
  end

  create_table "open_id_authentication_settings", :force => true do |t|
    t.column "setting", :string
    t.column "value",   :binary
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "rev",          :integer,  :default => 1,  :null => false
    t.column "name",         :string,   :default => "", :null => false
    t.column "created_at",   :datetime,                 :null => false
    t.column "login_at",     :datetime
    t.column "role",         :integer,  :default => 1,  :null => false
    t.column "identity_url", :string,   :default => "", :null => false
  end

end
